# https://github.com/golang/go/wiki/GoArm
# https://hub.docker.com/r/arm64v8/alpine/tags
FROM arm64v8/golang:1.24.3-alpine3.21 AS builder

WORKDIR /build
COPY . .
RUN go mod download
RUN go build .

FROM arm64v8/golang:1.24.3-alpine3.21

WORKDIR /app
COPY --from=builder /build/main .

ENTRYPOINT ["/app/main"]
